### ISSUE TITLE
Error when trying to start app

### ISSUE THREAD

**Issue by aqualxx** [ScottPeterJohnson/gpt2-discord#4]
I have been trying to use and tinker with this app for hours, but cannot seem to find a solution to this problem I am having. Log report:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
SLF4J: Defaulting to no-operation MDCAdapter implementation.
SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
[main] INFO JDA - Login Successful!
[JDA MainWS-ReadThread] INFO WebSocketClient - Connected to WebSocket
Traceback (most recent call last):
  File "src/bot_samples.py", line 85, in <module>
    fire.Fire(interact_model)
  File "/usr/local/lib/python3.5/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.5/dist-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.5/dist-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "src/bot_samples.py", line 47, in interact_model
    enc = encoder.get_encoder(model_name, models_dir)
  File "/gpt-2/src/encoder.py", line 110, in get_encoder
    encoder = json.load(f)
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by aqualxx** [comment]
Fixed in PR for your gpt-2 fork: https://github.com/ScottPeterJohnson/gpt-2/pull/1
